### ISSUE TITLE
Set Access-Control-Allow-Origin header to allow requests

### ISSUE THREAD

**Issue by jeremypuchta** [jeremypuchta/leipzig-tech-ba#38]
When I try to submit a request from the client to GET "/companies" with the new filtering feature I receive the error which is displayed in the attached screenshot. 

To resolve this issue it's probably necessary to set the Access-Control-Allow-Origin header to '*'. More about that here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin 

![image](https://user-images.githubusercontent.com/17340361/104060931-f4288400-51f7-11eb-87fb-340fd190a9f1.png)

**Comment by Fabbby** [comment]
new branch with fix available
